tabWidth: 2
semi: true
singleQuote: true
printWidth: 140
endOfLine: lf
overrides:
  - files: '**/*.{yaml,yml,js,jsx,ts,tsx}'
    options:
      tabWidth: 2
  - files: '**/package.json'
    options:
      tabWidth: 2
      singleQuote: false
  - files: '**/*.{json,jsonc,md,code-snippets,code-workspace}'
    options:
      trailingComma: none
  - files: '**/*.{html,css,scss}'
    options:
      tabWidth: 2
      singleQuote: false
