packages:
  - website

minimumReleaseAge: 2880 # two days
minimumReleaseAgeExclude:
  - '@cspell/dict-*'
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - webpack-dev-middleware@7.4.6

allowBuilds:
  # '@parcel/watcher': false
  # '@swc/core': true
  core-js: false
  esbuild: true
  # skia-canvas: false
  # unrs-resolver: true

# cspell:dictionaries npm
# cspell:ignore webpackbar unrs
