name: ' 🧽 Lint'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node, PNPM, and Corepack
        uses: streetsidesoftware/actions/public/setup-node-pnpm-corepack@v1

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint
