name: ' 🔗 Update Dependencies Main'

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '**/pnpm-lock.yaml'
      - 'scripts/**'
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'

permissions:
  contents: read

jobs:
  update-dependencies:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: 'update-dependencies-main'
      REF_BRANCH: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Setup Node, PNPM, and Corepack
        uses: streetsidesoftware/actions/public/setup-node-pnpm-corepack@v1

      - name: Install
        run: pnpm install

      - name: Update
        run: |
          pnpm -r up

      - name: Install
        run: |
          pnpm i

      - name: Lint
        run: |
          pnpm lint:fix

      - name: PR Body
        id: body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: Update Dependencies
          path: >-
            package.json
            website/package.json

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: 'ci: Workflow Bot -- Update ALL Dependencies'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          body: ${{ steps.body.outputs.body }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
